version: '3.8'  # Versão do Docker Compose (ajuste conforme necessário)

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projeto
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-net

  web:
    image: matheuswbz78/web-app:latest
    container_name: web
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-net

  report:
    image: matheuswbz78/report-app:latest
    container_name: report
    restart: always
    depends_on:
      - db
    ports:
      - "4040:4040"
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
